// <auto-generated />
using Cinema_Calc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinema_Calc.Migrations
{
    [DbContext(typeof(ApplicationDpContext))]
    partial class ApplicationDpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinema_Calc.Models.Expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Percentage_Markup")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Expense 1",
                            Percentage_Markup = 11.0,
                            Price = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Expense 2",
                            Percentage_Markup = 12.0,
                            Price = 200.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Expense 3",
                            Percentage_Markup = 13.0,
                            Price = 300.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Expense 4",
                            Percentage_Markup = 14.0,
                            Price = 400.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Expense 5",
                            Percentage_Markup = 15.0,
                            Price = 500.0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Expense 6",
                            Percentage_Markup = 16.0,
                            Price = 600.0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Expense 7",
                            Percentage_Markup = 17.0,
                            Price = 700.0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Expense 8",
                            Percentage_Markup = 18.0,
                            Price = 800.0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Expense 9",
                            Percentage_Markup = 19.0,
                            Price = 900.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
